### ISSUE TITLE
[Question]  I don't get messages on Telegram.

### ISSUE THREAD

**Issue by LionZXY** [DaniW42/motioneye-telegram#28]
# Description

I set everything up according to the instructions, but I just don't get the message when I move. Even though the script is called.

# Step to reproduce
- Install script by `README.md`
- Set up motioneye notification with command `/home/pi/motioneye-telegram/bin/motion-send.sh %$ %t`
<img width="555" alt="image" src="https://user-images.githubusercontent.com/5871715/110384757-c2506400-8066-11eb-8c9c-38fcd88143b6.png">
- Do some motion
- See logs

# Expected behaviour
Telegram video and images sent

# Actual behaviour
Nothing happens. In `/home/pi/motioneye-telegram/motion-send.log` i see this:
```
=========================================================
Mon 08 Mar 2021 11:34:35 PM EET - MOTION DETECTED by Camera Camera2.
Mon 08 Mar 2021 11:34:35 PM EET - Device available, end script.
=========================================================
```

I'm not sure I understand how this script works. Can you tell me what I'm doing wrong?

**Comment by LionZXY** [comment]
I am not sure about `bug` label. This label assigned automatically

**Comment by DaniW42** [comment]
while running the install-tg.sh script it should have asked you for an ip adress of devices or something similar. 

please try to disconnect your phone or laptop from WiFi (the one with the ip addresses you entered), wait a couple of minutes (up to five) and move again in front of the camera. 

does it send a picture and video?

BTW, thank you for creating that issue so others might be able to have a look into this. 👌

**Comment by LionZXY** [comment]
What IP I should use? External (to my router) or internal (device ip like 192.168.1.52)?

**Comment by talentpierre** [comment]
you should use the internal ip address of your smartphone.
the script pings your smartphone and look if it is connected to your wifi.
if your smartphone is not connected to your wifi the script cannot ping it and therefore should send you a message.
you should only get a message if you are not connected to your wifi. 
as the screenshot you provided states, your smartphone seems to be connected and therefore no script will be sent

**Comment by LionZXY** [comment]
Thank you! It really helped me!
But now i see that message don't send for me in telegram:
```
=========================================================
Thu 11 Mar 2021 08:47:56 PM EET - MOTION DETECTED by Camera Camera2.
Thu 11 Mar 2021 08:47:56 PM EET - Device NOT available, RUN script.
Thu 11 Mar 2021 08:47:56 PM EET - $lastsnap is 
Thu 11 Mar 2021 08:47:56 PM EET - $lastvideo is 
Thu 11 Mar 2021 08:47:56 PM EET - BEGIN tg-sendPhoto.py:
Thu 11 Mar 2021 08:47:56 PM EET - BEGIN tg-sendVideo.py:
=========================================================
```
Maybe some issue with motioneye settings?

**Comment by LionZXY** [comment]
Okay, I found the reason. For some reason motioneye transmits the id as one, even though I have it explicitly set to id 2.

**Comment by DaniW42** [comment]
Weird, so it is working now? How did you find out?

**Comment by LionZXY** [comment]
Yes, it works now. I couldn't find the error, however, I just hardcoded the variables in the script. I think I can close the discussion. Thank you for your help!

**Comment by markosc** [comment]
i have this message  ![image](https://user-images.githubusercontent.com/16872280/187016744-855812d7-71c4-46e8-9816-2debcfbf88ac.png)
I don't know why it doesn't detect it

but when I enter the panel if I can see that the camera works well
![image](https://user-images.githubusercontent.com/16872280/187016802-902ad0a1-aa72-4a90-b2e6-178e05e60e83.png)
