### ISSUE TITLE
Test works but no pictures are sent

### ISSUE THREAD

**Issue by opandroids** [DaniW42/motioneye-telegram#30]
**Describe your problem**
A clear and concise description of what is working and what is not.

**To Reproduce**

**Expected behavior**
Install works api and chat token provided. Run an end command with correct directory provided.

**Raspberry (please complete the following information):**
 - Raspberry Pi OS:Raspbian buster 10

***optional***
 Pi4

**Additional context**
Could it be that my ssh isn't the default port? The test gets sent i managed to get 2 pictures sent but besides that nothing i trigger motion detection it saves on MotioneyeOS but never seems to sent it to my telegram bot. 

according to the logs
&: /home/debianpi/motioneye-telegram/bin/motion-send.sh: No such file or directory
 &: /home/debianpi/motioneye-telegram/bin/motion-send.sh: No such file or directory

but on my pi
debianpi@raspberrypi:~/motioneye-telegram/bin $ pwd
/home/debianpi/motioneye-telegram/bin

**Comment by DaniW42** [comment]
Oh.. I am very sorry but I missed this... Did you managed to get it running?

If not and you are still in need of help, could it be access related? Is the user you are running the script with able to access the directory?

**Comment by DaniW42** [comment]
As there was no answer, we are closing this. BTW, MotioneyeOS might work different in some parts. We have never tested it to run on MotioneyeOS.
