### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Nuke142** [DaniW42/motioneye-telegram#34]
Can you take your job to Docker? Besides, Docker already have wonderful telegram-bot-api container https://hub.docker.com/r/aiogram/telegram-bot-api

**Comment by DaniW42** [comment]
Hey, 

this would be nice but it won't happen. This project only contains some lines of code and a config file. Using Docker we would have to deal with a motioneye container triggering another container which only holds a bash script to then send a file from the first container to an telegram container.

But if you're in to Docker, I would love to see your approach.

**Comment by DaniW42** [comment]
@talentpierre, do you agree?

**Comment by talentpierre** [comment]
I agree. a docker container only for some scripts has to much overhead.

**Comment by Nuke142** [comment]
I'am aliasing Unraid OS - this is popular proprietary OS where that you just can't download and run script. Usually all done via docker or VM. That's why i am ask. Only way to use script is use Debian VM for it. So that is my way..
